---
- name: setup DNS servers 
  hosts: dns
  remote_user: root
  roles:
    - dns

- name: edit DNS parameters on web and lb
  hosts: web:lb
  tasks:
  - name: include task set_dns in play
    ansible.builtin.import_tasks:
      file: tasks/set_dns.yml

- name: setup web load balancer
  hosts: lb
  roles:
    - lb
  
- name: setup web servers
  hosts: web
  roles :
    - web