---
- name: Install bind9 (or update to latest version)
  ansible.builtin.package:
    name: bind9
    state: latest

- name: get timestamp on 1 server for serial number
  ansible.builtin.shell:
    cmd: "date +%s"
  run_once: True
  register: timestamp

- name: generate zone file from jinja2 template and copy it on server
  ansible.builtin.template:
    src: templates/labzone.j2
    dest: /etc/bind/db.{{ domaine_lab }}
    owner: bind
    group: bind
    mode: '0644'
  notify: reload bind service

- name: edit named.conf.local file to add zone file
  ansible.builtin.blockinfile: 
    path: /etc/bind/named.conf.local
    backup: true
    block : |
      zone "{{ domaine_lab }}" {
        type master;
        file "/etc/bind/db.{{ domaine_lab }}";
      };
  notify: reload bind service